### ISSUE TITLE
How can I get the JSON blob from a request that returns 400?

### ISSUE THREAD

**Issue by weaversa** [paritytech/jsonrpsee#979] opened 2023-01-21 19:18 UTC
If I make the following request:
```
let response: MyResultJSONStruct = match client.request("my command", params).await {
        Ok(r) => r,
        Err(e) => panic!("{}", e),
      };
```
 and the server returns `400`, the `Err(e)` match will produce:
```
...Networking or low-level protocol error: Server returned an error status code: 400...
```

In my case, the server returns `400` as well as a JSON blob with a more detailed message about the error. I'm struggling to determine how to access the JSON blob (using jsonrpsee methods) on error. Any help would be appreciated.

**Comment by niklasad1** [comment] 2023-01-21 20:55
I think you mean that you want to read HTTP response body right?

The issue is that we throw away the HTTP response once it wasn't successful i.e, not status code 200-299

Closing as duplicate https://github.com/paritytech/jsonrpsee/issues/972, the intention is to add middleware to make that possible to inspect the HTTP request/response and more sophisticated things.

**Closed by niklasad1** 2023-01-21 20:55 UTC

**Comment by weaversa** [comment] 2023-01-21 21:02
Thanks @niklasad1. I think I do want to see the HTTP response body. How far out is the middleware addition on your roadmap? Just trying to get a sense of if/when this feature would arrive.

**Comment by niklasad1** [comment] 2023-01-21 21:19
Should be soon but I provided a branch https://github.com/paritytech/jsonrpsee/tree/na-http-client-response-body-log
which logs the response body by "trace level" but you need to use to the `tracing subscriber` for those to show up.

https://github.com/paritytech/jsonrpsee/tree/na-http-client-response-body-log
