### ISSUE TITLE
hyper13 and hyper14 compatibility

### ISSUE THREAD

**Issue by akru** [paritytech/jsonrpsee#254] opened 2021-03-28 04:30 UTC
Looks like the latest jsonrpsee has some compatibility issues with fresh hyper.

```
   Compiling jsonrpsee-utils v0.2.0-alpha.3                                                                                    
   Compiling hyper-rustls v0.20.0                                                                                              
   Compiling hyper-multipart-rfc7578 v0.4.0-rc                                                                                 
error: feature `hyper13` and `hyper14` are mutably exclusive                                                                   
 --> /home/akru/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonrpsee-utils-0.2.0-alpha.3/src/lib.rs:2:1                   
  |                                                                                                                            
2 | compile_error!("feature `hyper13` and `hyper14` are mutably exclusive");   
```

**Comment by dvdplm** [comment] 2021-03-28 08:35
Can you show your full Cargo.toml? Could it be your project has multiple versions of `hyper` in it?

**Comment by niklasad1** [comment] 2021-03-28 10:07
Please share your `Cargo.toml`, my guess it that you forgot to disable the default-features if you want to use `hyper13`.

Otherwise, it's bug on our end but I would surprised as [we test it in the CI](https://github.com/paritytech/jsonrpsee/blob/master/.github/workflows/ci.yml##L73-L77)

**Comment by akru** [comment] 2021-03-28 11:35
I use jsonrpsee as a dependency of https://github.com/paritytech/substrate-subxt (crates package version `0.15`). I guess it conflicts with something from https://github.com/airalab/robonomics, maybe https://docs.rs/ipfs-api/0.11.0/ipfs_api/

**Comment by niklasad1** [comment] 2021-03-28 12:56
Ok, I see.

`subxt` uses tokio1.0/hyper14 and `robonoimcs (substrate)` uses tokio0.2/hyper13 thus you will end-up with both `hyper13 and hyper14` features which causes it not to compile.

I suppose `subxt` can make it configurable to work with `tokio 0.2 or tokio 1.0` until the entire ecosystem has upgraded to tokio 1.0

**Comment by niklasad1** [comment] 2021-04-11 10:04
Closing this as this works as intended i.e, `tokio0.2` and `tokio1` is mutually exclusive and only one should be enabled.

Please file an issue in https://github.com/paritytech/substrate-subxt instead to make it configurable with `tokio 0.2`

**Closed by niklasad1** 2021-04-11 10:04 UTC
