### ISSUE TITLE
Macros error

### ISSUE THREAD

**Issue by Pierre-Green** [paritytech/jsonrpsee#1221] opened 2023-10-22 15:51 UTC
Hello,
I've started to use jsonrpsee recently. I've created a common cargo crate in my workspace with my Rpc traits and this crate is used in a leptos wasm app and in a tokio backend.
I've tried to write a macro_rules! to conditionally include the RpcServer in the decorator macro as follow:

```rust
use jsonrpsee::proc_macros::rpc;
use jsonrpsee_types::error::ErrorObjectOwned;

macro_rules! rpc_trait {
    ($visibility:vis trait $name:ident {$($body:tt)*}) =>
    {
        #[cfg(not(feature = "server"))]
        mod trait_definition {
            use super::*;

            #[rpc(client)]
            #[async_trait]
            $visibility trait $name {
                $($body)*
            }
        }

        #[cfg(feature = "server")]
        mod trait_definition {
            use super::*;

            #[rpc(server, client)]
            #[async_trait]
            $visibility trait $name {
                $($body)*
            }
        }

        pub use trait_definition::*;
    };
}

rpc_trait! {
    pub trait BrainRpc {
        #[method(name = "getStatus")]
        async fn get_status(&self) -> Result<(), ErrorObjectOwned>;
    }
}
```

but I have the following error:
```
error[E0425]: cannot find value `__self` in this scope
  --> shared/brain-rpc/src/lib.rs:22:13
   |
22 |               #[rpc(server, client)]
   |               ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
...
33 | / rpc_trait! {
34 | |     pub trait BrainRpc {
35 | |         #[method(name = "getStatus")]
36 | |         async fn get_status(&self) -> Result<(), ErrorObjectOwned>;
37 | |     }
38 | | }
   | |_- in this macro invocation
   |
   = note: this error originates in the attribute macro `rpc` which comes from the expansion of the macro `rpc_trait` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Does someone have any idea of a way to fix it ?

**Comment by niklasad1** [comment] 2023-10-22 17:10
You could just do:

```rust
#[cfg_attr(feature = "server", rpc(client, server))]
#[cfg_attr(not(feature = "server"), rpc(client))]
pub trait BrainRpc {
	#[method(name = "getStatus")]
	async fn get_status(&self) -> Result<(), ErrorObjectOwned>;
}
```

I think the `#[async_trait]` stuff on the jsonrpsee needs to be elided but looks like the path to jsonrpsee  after that
you moved to another module.

**Comment by niklasad1** [comment] 2024-05-31 08:49
Smaller reproducation of this 

```rust
macro_rules! rpc_trait {
	($visibility:vis trait $name:ident {$($body:tt)*}) =>
	{
		mod trait_definition {
			use super::*;

			#[rpc(client)]
			$visibility trait $name {
				$($body)*
			}
		}

		pub use trait_definition::*;
	};
}

rpc_trait! {
	pub trait BrainRpc {
		#[method(name = "getStatus")]
		async fn get_status(&self) -> Result<(), ErrorObjectOwned>;
	}
}
```

This expands to 


```rust
mod trait_definition {
    use super::*;
    ///Client implementation for the `BrainRpc` RPC API.
    pub trait BrainRpcClient: jsonrpsee::core::client::ClientT {
        #[allow(non_snake_case)]
        #[allow(clippy::used_underscore_binding)]
        #[must_use]
        #[allow(
            clippy::async_yields_async,
            clippy::diverging_sub_expression,
            clippy::let_unit_value,
            clippy::no_effect_underscore_binding,
            clippy::shadow_same,
            clippy::type_complexity,
            clippy::type_repetition_in_bounds,
            clippy::used_underscore_binding
        )]
        fn get_status<'life0, 'async_trait>(
            &'life0 self,
        ) -> ::core::pin::Pin<
            Box<
                dyn ::core::future::Future<
                    Output = Result<(), jsonrpsee::core::client::Error>,
                > + ::core::marker::Send + 'async_trait,
            >,
        >
        where
            'life0: 'async_trait,
            Self: ::core::marker::Sync + 'async_trait,
        {
            Box::pin(async move {
                if let ::core::option::Option::Some(__ret) = ::core::option::Option::None::<
                    Result<(), jsonrpsee::core::client::Error>,
                > {
                    #[allow(unreachable_code)] return __ret;
                }
                let __self = self;
                let __ret: Result<(), jsonrpsee::core::client::Error> = {
                    let params = { { jsonrpsee::core::params::ArrayParams::new() } };
                    __self.request("getStatus", params).await
                };
                #[allow(unreachable_code)] __ret
            })
        }
    }
    impl<TypeJsonRpseeInteral> BrainRpcClient for TypeJsonRpseeInteral
    where
        TypeJsonRpseeInteral: jsonrpsee::core::client::ClientT,
    {}
}
pub use trait_definition::*;
```

The generated code works by itself so I don't really follow why it doesn't work but with that said it it isn't an
codegen issue and jsonrpsee so closing this

**Closed by niklasad1** 2024-05-31 08:49 UTC
