### ISSUE TITLE
`SubscriptionSink.send` does not return error for disconnected client.

### ISSUE THREAD

**Issue by kukabi** [paritytech/jsonrpsee#481] opened 2021-09-21 13:56 UTC
Steps to reproduce:
1. Add a subscription method to the `RpcModule` with `register_subscription` . The loop in the inner spawned thread sends to the `SubscriptionSink` at regular intervals.
2. Subscribe from the client, server starts publishing values.
3. Disconnect the client without unsubscribing.
4. The spawned thread still can `send` to the `SubscriptionSink` and unexpectedly receives `Ok(())`.

If the client had unsubscribed then `send` expectedly returns `Err`.

_Note:_ Tested with `WsServerBuilder`.

**Comment by niklasad1** [comment] 2021-09-21 14:11
Thanks, yepp I could reproduce this and I agree.

Weird I thought I wrote a test for this but it was for the other way around.

**Comment by niklasad1** [comment] 2021-09-21 22:44
I checked this and it's a `ws client` bug when the client is dropped we should send unsubscribe requests to all active subscriptions then the server will remove the subscription and not continue to send out the messages that the client is not interested in anymore.

For now, you have to `drop` the subscriptions manually in order for this to work but I will fix this tomorrow, should be quite easy to fix.

**Comment by kukabi** [comment] 2021-09-22 20:47
Thanks a lot @niklasad1, I follow the edit in your comment, as the service provider I don't ever have access to how the clients handle their subscription/connection, and even if they handled the subscription properly they could also abruptly lose connection.

Not sure if it's ready but I just gave `na-fix-481` a try, there's a new error message `rx ws data failed: Closed; closing connection` when I cut the connection at the server side before any unsubscription, yet I'm still able to `send` to the `SubscriptionSink`. It returns `Ok`.

**Comment by niklasad1** [comment] 2021-09-23 05:56
Yeah, I can probably remove that error message is just that the client closed the connection we didn't have that log before.

The issue on the server side is basically when we create subscription the `mpsc::Sender` is cloned and put in the Hashmap in the `rpc module (outside the server struct called)` and that subscription will not be possible to close (because the strong count on mpsc::Sender will be bigger > 1) without sending an unsubscribe request to it. For instance when a connection is closed by the client those subscriptions will "be alive" because the all the senders of that channel is not dropped and `SubscriptionSink::send` will not return an error.

Thus, the correct fix would be better if the ws server would remove all subscriptions associated with the connection ID that got closed (the subscription IDs are not known by the server currently) then `SubscriptionSink::send` will return error.

But that requires some more refactoring and might that a little longer to fix.

**Comment by niklasad1** [comment] 2021-09-28 20:05
Fixed by #483

**Closed by niklasad1** 2021-09-28 20:05 UTC
