### ISSUE TITLE
Transport RequestFailure status_code

### ISSUE THREAD

**Issue by tsfotis** [paritytech/jsonrpsee#605] opened 2021-12-13 17:34 UTC
How can i get the status_code when a Transport(RequestFailure{}) is returned?
I cannot use downcast_ref because jsonrpsee_http_client::transport is public only to the crate.

**Comment by niklasad1** [comment] 2021-12-13 19:29
right,

@tsfotis the issue is that the error type not public right?

Feel free to open a PR to make [this pub]https://github.com/paritytech/jsonrpsee/blob/master/http-client/src/transport.rs#L131and re-export it from the http client.

**Comment by niklasad1** [comment] 2021-12-17 14:44
Closed by #607

**Closed by niklasad1** 2021-12-17 14:44 UTC
