### ISSUE TITLE
Defining a notification first fails to compile

### ISSUE THREAD

**Issue by SirWindfield** [paritytech/jsonrpsee#89] opened 2020-02-01 23:01 UTC
I defined a notification method first inside of the `rpc_api` macro. This does result in a compilation error. Below the code snippet to reproduce:

```rust
jsonrpsee::rpc_api! {
    Logging {
        fn info(msg: String);
    }
}

fn main() {
    env_logger::try_init().ok();
    // Spawning a server in a background task.
    async_std::task::spawn(async move {
        let listen_addr = "127.0.0.1:8000".parse().unwrap();
        let mut server1 = jsonrpsee::http_raw_server(&listen_addr).await.unwrap();

        while let Ok(request) = Logging::next_request(&mut server1).await {
            match request {
                Logging::Info{ msg } => {
                    println!("{}", msg);
                }
            }
        }
    });

    // Client demo.
    let mut client = jsonrpsee::http_raw_client("http://127.0.0.1:8000");
    let v = async_std::task::block_on(async {
        Logging::info(&mut client, "some random message")
            .await
            .unwrap();
    });
    println!("{:?}", v);
}
```

Compiler error:

```
error[E0282]: type annotations needed
  --> src/lib.rs:30:29
   |
30 |     while let Ok(request) = Logging::next_request(&mut server).await {
   |                             ^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `R`

error[E0282]: type annotations needed
  --> src/lib.rs:10:5
   |
10 | /     Logging {
11 | |         // fn enable(value: bool) -> bool;
12 | |
13 | |         fn info(msg: String);
   | |_______________^ cannot infer type for `R`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0282`.
error: could not compile `embedded-server`.

To learn more, run the command again with --verbose.
```

Adding a request above the notification makes the program compile (as seen in the http example).

**Comment by niklasad1** [comment] 2021-03-01 16:22
Hey, thanks for reporting but this example looks very old and it is a duplicate of https://github.com/paritytech/jsonrpsee/issues/104.

So closing this in favor of #104

**Closed by niklasad1** 2021-03-01 16:22 UTC
